use_frameworks!

platform :ios, '9.0'

target 'MikuKit_Example' do
  pod 'MikuKit', :path => '../'

  target 'MikuKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
